name: Release
on:
  push:
    branches: [main]

permissions:
  contents: read # para checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # para publicar un release en GitHub
      issues: write # para comentar en issues lanzados
      pull-requests: write # para comentar en PR lanzados
      id-token: write # para habilitar el uso de OIDC para la procedencia de npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: yarn install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: yarn audit --level high || true
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
